#!/usr/bin/env node
/**
 * Bundles the SQL Explorer source (`src/`) into the single `extension.js`
 * artifact that TEDI loads (the host reads only `manifest.main` and imports it
 * as one ES module, so the shipped extension must be a single file).
 *
 * Usage:
 *   node build.mjs            # one-shot build → extension.js
 *   node build.mjs --watch    # rebuild on every src/ change (dev)
 *
 * The output is intentionally NOT minified: extension.js is the artifact users
 * install (CI bundles it into the release .zip; it is NOT committed), and an
 * unminified bundle keeps the shipped/installed code readable and debuggable.
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build, context } from "esbuild";

const root = path.dirname(fileURLToPath(import.meta.url));

/** @type {import("esbuild").BuildOptions} */
const options = {
  entryPoints: [path.join(root, "src", "index.js")],
  outfile: path.join(root, "extension.js"),
  bundle: true,
  format: "esm", // loader does `import(blobUrl)` and reads `activate` / `deactivate`
  platform: "browser",
  target: "es2022",
  charset: "utf8",
  legalComments: "none",
  minify: false,
  logLevel: "info",
  banner: {
    js: [
      "// @generated by build.mjs — DO NOT EDIT THIS FILE DIRECTLY.",
      "// Source lives in src/; run `npm run build` after editing.",
      "// Repo: https://github.com/IlhamriSKY/TEDI.sql-explorer",
    ].join("\n"),
  },
};

if (process.argv.includes("--watch")) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("[build] watching src/ → extension.js (Ctrl+C to stop)");
} else {
  await build(options);
  console.log("[build] wrote extension.js");
}
